jobs:
  build:
    if: '! contains(toJSON(github.event.commits.*.message), ''[skip ci]'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: 1. Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: 2. Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: 3. Perform build
      run: ./gradlew -i build
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PGP_KEY: ${{secrets.PGP_KEY}}
        PGP_PWD: ${{secrets.PGP_PWD}}
        SONATYPE_PWD: ${{secrets.SONATYPE_PWD}}
        SONATYPE_USER: ${{secrets.SONATYPE_USER}}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository
        == 'linkedin/coral' && !contains(toJSON(github.event.commits.*.message), '[skip
        release]')
      name: 4. Perform release
      run: ./gradlew githubRelease publishToSonatype closeAndReleaseStagingRepository
        --stacktrace
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
